### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#22]
It just does not do anything maybe because of some Rust update?

**Comment by alexander171294** [comment]
This is strange, i can connect without problems,

ensure if you are connecting without ssl, because if you are using https then you can't connect to a socket without ssl like rust server.

**Comment by Bazimek** [comment]
I have on my website https turned on but when I go to the website with Rust Monitor it automaticly go to http not https so it should work? But it is just do nothing when I click on connect.

**Comment by alexander171294** [comment]
neither shows the spinner of connection? check if in the chrome inspector (right click, inspect website), in the tab of networking, check if show an error connecting to your server IP.

**Comment by alexander171294** [comment]
I used this link http://rustmon.tandilserver.com/#/connector to connect to my server and works fine.

Can you send me your link to try connect to my server?

In the last update i added some features, but I don't touch the connection websocket code.

**Comment by alexander171294** [comment]
> I have on my website https turned on but when I go to the website with Rust Monitor it automaticly go to http not https so it should work? But it is just do nothing when I click on connect.

Yes, if you use http:// without ssl even if you support ssl, then should work

**Comment by alexander171294** [comment]
check if you have web rcon enabled in rust server command line,  rcon.web true

**Comment by Bazimek** [comment]
Yes I have like from rcon.io I can normally connect or with other rcon tools.

**Comment by alexander171294** [comment]
![image](https://user-images.githubusercontent.com/2080955/146998342-466c72e2-c8e1-4d18-82d0-241e2689dcaf.png)

I can connect without problems :(

**Comment by Bazimek** [comment]
Can you test it from this rcon.gamearea.cz?

**Comment by alexander171294** [comment]
I can't access to that url without use ssl, because this page automatically redirect me to https:// with an invalid ssl.

If you have invalid ssl you are using SSL and i think, that is the problem i think.

let me create an update in order to try fix it.

**Comment by Bazimek** [comment]
Oh thank you for your work and help. :-) This is the best rcon tool and I love it.

**Comment by alexander171294** [comment]
Well I updated now the script adding instructions to connect from a website with https (in the connection page), but i'm not sure why your website automatically try to connect to a wss:// and this is making problems.

Try to fix your ssl and update the script in order to fix the problem.

If you have implemented new feature and you want to share with us, you can send me the source with new features and I will try to add that features to the project.

I added in the last updates (days ago), new features like, chat mute, and sub-menu to order the actions like add mods, and I added flags to see from where is the ip.

**Comment by Bazimek** [comment]
I am using the last version from there, and the SSL is normally working on my website and other subwebsites. The website needs to be made for ssl/https. I have valid SSL certificate active on this domain.

**Comment by alexander171294** [comment]
but in this case, when i open your website I get an invalid ssl:

![image](https://user-images.githubusercontent.com/2080955/147001522-7728d9ab-28c1-45ac-a3ae-a1a730f435cc.png)

And your server is automatically adding this:
![image](https://user-images.githubusercontent.com/2080955/147001622-1e825d95-f16a-471d-9501-04751ee6b70c.png)

wss, but in the code says ws://
![image](https://user-images.githubusercontent.com/2080955/147001654-ce16fcfd-b5be-4af9-877a-fc3bd8c624c3.png)

and in the tandilserver versions, i can connect and see connection to:
![image](https://user-images.githubusercontent.com/2080955/147001770-3853a0de-6b08-4153-a67a-a68cfe16ea81.png)

as you see, for a unknown reason, your website is adding ws**S** to a connection string, and that is strange, idk why that happens.

Yes you are right, you have the last version srry.

**Comment by alexander171294** [comment]
I'm trying to find a reason that explain why your website is adding a "S" in the connection string, because that happens only in your website :(

**Comment by Bazimek** [comment]
You are right, I found something with the SSL. Give me a minute for the certifiace on this subdomain.

**Comment by alexander171294** [comment]
I'm would like to add a map with position of players, but I don't know how can i do that :(

**Comment by Bazimek** [comment]
Oh I think that wont be possible without oxide plugin on the server.

**Comment by Bazimek** [comment]
OK the SSL is now working for me, but still can't connect.

**Comment by alexander171294** [comment]
I have a question, why are you running a development version?, how do you host the project?

are you using "ng build --prod" to build the distributables files? or are you using "ng build" only?, because Angular recommends to you to use the flag --prod in order to build to production.

I think that is the only one difference between your website and mine, and idk why in your website i can't connect but in my website i can, i think it is because one script is changing the connection schema from "ws://" to "wss://", can be because you are using development version.

check that.

Sorry but the problem it's really strange :(, if that is not the problem, can be the webserver or some like that, one security header o so.

**Comment by Bazimek** [comment]
I used npm build --prod I think, the ng build --prod just open some new file or something for me. And I host it in my hosting provider (the files from dist folder).

**Comment by alexander171294** [comment]
okay, I suspect that you didn't use --prod in the last update, because when I opened the javascript console in your website, I saw this message from angular framework:

`Angular is running in the development mode. Call enableProdMode() to enable the production mode.`

That means you aren't using production, I'm viewing the angular web page in order to check if the flag --prod has changed to another flag, but can you try to rebuild the project using that flag?

And maybe that is the problem.

**Comment by Bazimek** [comment]
When I use ng build --prod it just open some text editor? Give me a sec.

**Comment by alexander171294** [comment]
try this: npm run buildprod

**Comment by Bazimek** [comment]
I run npm run build -- --prod it did something, but still can't connect.

**Comment by Bazimek** [comment]
I Build it from beggining now correctly with ng build --prod .. but still it is not working for me :(

**Comment by alexander171294** [comment]
Okay, i found the problem, I see in firefox that the server (your apache or webserver) is sending "Content-Security-Policy" header:

`content-security-policy: upgrade-insecure-requests;`

And as say in this post: https://stackoverflow.com/questions/31950470/what-is-the-upgrade-insecure-requests-http-header

This can be the reason because the websocket is trying to use ssl with rust ip, 

My server headers that works:
![image](https://user-images.githubusercontent.com/2080955/147008674-0696080c-f647-4820-b107-3b22e998d721.png)

Your server headers that doesn't work:
![image](https://user-images.githubusercontent.com/2080955/147008702-65c4fde7-0e37-4292-bd32-73dbfc1ec315.png)

I think that can be fixed with a configuration in apache in a .htaccess file:

`Header unset Content-Security-Policy`

or

`Header always unset Content-Security-Policy`

Then remember to allow the use of insecure content (the connection to rust server rcon is insecured) following this article:

https://www.damirscorner.com/blog/posts/20210528-AllowingInsecureWebsocketConnections.html

**Comment by alexander171294** [comment]
I think you added the .htaccess, now i can connect from firefox, but from chrome i can't because i think that have a cache o some like that, because when I try in other pc, now i can connect without a problem, check the photo:

![image](https://user-images.githubusercontent.com/2080955/147010367-a71f45b2-647f-4b2c-802b-b433d3fe4d93.png)

**Comment by Bazimek** [comment]
Yes I added to the subdomain the htaccess but it does not work for me. I am using Edge.

**Comment by alexander171294** [comment]
yes it's because your browser is saving your headers and ignoring deletion,

https://stackoverflow.com/questions/33014574/how-to-force-a-browser-to-get-new-headers-without-declaring-expires

As you see, you can't do nothing to fix that in your browser, i think you can try to change the domain to rcon2 or so, or use other browser.

Or you can add a proxy like nginx reverse proxy, to add wss to your rust server.

**Comment by Bazimek** [comment]
Thank you, I did the tutorial from your website then I turn off the SSL and it can atleast connect now. :-) Thank you.
